const series = [
    { title: "Breaking Bad", rating: 9.5, genre: "Dráma" },
    { title: "Stranger Things", rating: 8.7, genre: "Sci-fi, Horror, Thriller" },
    { title: "The Crown", rating: 8.6, genre: "Történelmi, Dráma" },
    { title: "Black Mirror", rating: 8.8, genre: "Sci-fi, Antológia" },
    { title: "The Mandalorian", rating: 8.8, genre: "Sci-fi, Akció, Kaland" },
    { title: "Fleabag", rating: 8.7, genre: "Vígjáték, Dráma" },
    { title: "Mindhunter", rating: 8.6, genre: "Bűnügyi, Dráma, Thriller" },
    { title: "Chernobyl", rating: 9.4, genre: "Dokumentum, Dráma, Történelmi" },
    { title: "Game of Thrones", rating: 9.3, genre: "Fantasy, Dráma, Kaland" },
    { title: "The Witcher", rating: 8.2, genre: "Akció, Kaland, Fantasy" },
    { title: "Narcos", rating: 8.8, genre: "Bűnügyi, Dráma, Thriller" },
    { title: "The Office", rating: 8.9, genre: "Vígjáték" },
    { title: "Sherlock", rating: 9.1, genre: "Bűnügyi, Dráma, Misztikus" },
    { title: "The Simpsons", rating: 8.7, genre: "Animáció, Vígjáték" },
    { title: "Friends", rating: 8.9, genre: "Vígjáték, Romantikus" },
    { title: "Westworld", rating: 8.6, genre: "Dráma, Sci-fi, Western" },
    { title: "Stranger Things", rating: 8.7, genre: "Sci-fi, Horror, Thriller" },
    { title: "Money Heist", rating: 8.3, genre: "Akció, Bűnügyi, Dráma" },
    { title: "The Big Bang Theory", rating: 8.1, genre: "Vígjáték" },
    { title: "Ozark", rating: 8.4, genre: "Bűnügyi, Dráma, Thriller" },
    { title: "The Umbrella Academy", rating: 8.0, genre: "Akció, Dráma, Fantasy" },
    { title: "The Sopranos", rating: 9.2, genre: "Bűnügyi, Dráma" },
    { title: "Fargo", rating: 8.9, genre: "Bűnügyi, Dráma, Thriller" },
    { title: "Rick and Morty", rating: 9.2, genre: "Animáció, Kaland, Sci-fi" },
    { title: "The Haunting of Hill House", rating: 8.6, genre: "Dráma, Horror, Misztikus" },
    { title: "Daredevil", rating: 8.6, genre: "Akció, Bűnügyi, Dráma" },
    { title: "Black Panther", rating: 9.0, genre: "Akció, Kaland, Sci-fi" },
    { title: "The Boys", rating: 8.7, genre: "Akció, Dráma, Sci-fi" },
    { title: "Breaking Bad", rating: 9.5, genre: "Dráma" },
    { title: "BoJack Horseman", rating: 8.7, genre: "Animáció, Dráma, Vígjáték" },
    { title: "The Witcher", rating: 8.2, genre: "Akció, Kaland, Fantasy" }
];
